apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: mcwvl60p5-go 
  janus-idp.io/tekton: mcwvl60p5-go
  backstage.io/kubernetes-id: mcwvl60p5-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: mcwvl60p5-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml